# Generated by Django 6.0.5 on 2026-05-26 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('source', models.CharField(help_text='Data provider e.g. Bloomberg, Reuters, Manual', max_length=100)),
                ('year', models.IntegerField(help_text='Fiscal year of the data')),
                ('carbon_emissions', models.FloatField(blank=True, help_text='CO₂ equivalent in metric tons', null=True)),
                ('energy_consumption', models.FloatField(blank=True, help_text='Energy used in MWh', null=True)),
                ('water_usage', models.FloatField(blank=True, help_text='Water used in cubic meters', null=True)),
                ('employee_count', models.IntegerField(blank=True, help_text='Number of full-time employees', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('suspicious_reason', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'ESG Record',
                'verbose_name_plural': 'ESG Records',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('performed_by', models.CharField(default='System', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, default='')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='records.esgrecord')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
