# Generated by Django 6.0.5 on 2026-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='activity_type',
            field=models.CharField(default='general', help_text='e.g. fuel_combustion, electricity_consumption, business_travel', max_length=60),
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='created_by',
            field=models.CharField(blank=True, default='System', max_length=100),
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='normalized_emissions',
            field=models.FloatField(blank=True, help_text='CO₂ equivalent in metric tons — unified across all source types', null=True),
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='original_source_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Original source-specific fields stored as JSON'),
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='scope_category',
            field=models.CharField(choices=[('scope_1', 'Scope 1 — Direct Emissions'), ('scope_2', 'Scope 2 — Purchased Energy'), ('scope_3', 'Scope 3 — Value Chain')], db_index=True, default='scope_1', max_length=20),
        ),
        migrations.AddField(
            model_name='esgrecord',
            name='source_type',
            field=models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility_electricity', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel'), ('generic', 'Generic ESG')], db_index=True, default='generic', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='esgrecord',
            name='carbon_emissions',
            field=models.FloatField(blank=True, help_text='Raw CO₂ in metric tons', null=True),
        ),
        migrations.AlterField(
            model_name='esgrecord',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esgrecord',
            name='source',
            field=models.CharField(help_text='Data provider name e.g. SAP, EDF Meter, Concur', max_length=100),
        ),
        migrations.AlterField(
            model_name='esgrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=20),
        ),
    ]
